import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";

const initialState = {
    jwt: sessionStorage.getItem("jwtToken") || "",
    loginStatus: "",
    status: "idle",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const loginAsync = createAsyncThunk("login/fetchUser", async (data) => {
    const response = await fetchUser(data.username, data.password);
    return response.token;
});

function fetchUser(username, password) {
    return new Promise((resolve) => {
        fetch("http://localhost:3000/login", {
            method: "POST", // or 'PUT'
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                user: {
                    username: username,
                    password: password,
                },
            }),
        })
            .then((data) => data.json())
            .then((data) => {
                resolve(data);
            });
    });
}

export const loginReducer = createSlice({
    name: "login",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        // increment: (state) => {
        //     // Redux Toolkit allows us to write "mutating" logic in reducers. It
        //     // doesn't actually mutate the state because it uses the Immer library,
        //     // which detects changes to a "draft state" and produces a brand new
        //     // immutable state based off those changes
        //     state.value += 1;
        // },
        // decrement: (state) => {
        //     state.value -= 1;
        // },
        // // Use the PayloadAction type to declare the contents of `action.payload`
        // incrementByAmount: (state, action) => {
        //     state.value += action.payload;
        // },
        logout: (state) => {
            sessionStorage.removeItem("jwtToken");
            state.jwt = "";
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(loginAsync.pending, (state) => {
                state.status = "loading";
            })
            .addCase(loginAsync.fulfilled, (state, action) => {
                state.status = "idle";
                if (action.payload === undefined) {
                    state.jwt = "";
                    state.loginStatus = "Bad username or password";
                } else {
                    state.jwt = action.payload;
                    sessionStorage.setItem("jwtToken", action.payload);
                    state.loginStatus = "";
                }
            });
    },
});

export const { logout } = loginReducer.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectJWT = (state) => {
    return state.login.jwt;
};
export const selectStatus = (state) => {
    return state.login.loginStatus;
};

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount) => (dispatch, getState) => {
//     const currentValue = selectCount(getState());
//     if (currentValue % 2 === 1) {
//         dispatch(incrementByAmount(amount));
//     }
// };

export default loginReducer.reducer;
